const images = [
  {
    name: "Template",
    src: "./images/template.jpeg",
    alt: "Template",
    favorite: false,
    number: 1,
    themes: ["Template"],
  },
  {
    name: "Assasiation Classroom",
    src: "./images/AC_modified.png",
    alt: "Assasiation Classroom",
    favorite: true,
    number: 2,
    themes: ["Manga", "Anime", "pancarte"],
  },
  {
    name: "Ares",
    src: "./images/Ares_modified.png",
    alt: "Ares",
    favorite: true,
    number: 2,
    themes: ["Astrologie"],
  },
  {
    name: "Death Note",
    src: "./images/Death_modified.png",
    alt: "Death Note",
    favorite: true,
    number: 2,
    themes: ["Manga", "Anime", "pancarte"],
  },
  {
    name: "Dragon Aquatique",
    src: "./images/dragon_originale.jpeg",
    alt: "Dragon Aquatique",
    favorite: true,
    number: 2,
    themes: ["Dragon", "Fantastique"],
  },
  {
    name: "Fairy Tail",
    src: "./images/fairy_modified.png",
    alt: "Fairy Tail",
    favorite: true,
    number: 2,
    themes: ["Manga", "Anime", "pancarte"],
  },
  {
    name: "Femme Juculaire",
    src: "./images/femme_modified.png",
    alt: "Femme Juculaire",
    favorite: false,
    number: 1,
    sensible: true,
    themes: ["Femme", "Suicide"],
  },
  {
    name: "Hunter X Hunter",
    src: "./images/hunter_modified.png",
    alt: "Hunter X Hunter",
    favorite: true,
    number: 2,
    themes: ["Manga", "Anime", "pancarte"],
  },
  {
    name: "Yuri on Ice",
    src: "./images/ice_modified.png",
    alt: "Yuri on ice",
    favorite: true,
    number: 2,
    themes: ["Manga", "Anime", "pancarte"],
  },
  {
    name: "Le Roi Lion",
    src: "./images/KingLion_originale.jpg",
    alt: "Le Roi Lion",
    favorite: true,
    number: 2,
    themes: ["Film", "Disney"],
  },
  {
    name: "Loup Tatoo",
    src: "./images/loup_originale.jpeg",
    alt: "Loup Tatoo",
    favorite: true,
    number: 2,
    themes: ["Simple", "Tatoo"],
  },
  {
    name: "phenix",
    src: "./images/phenix_modified.png",
    alt: "phenix",
    favorite: true,
    number: 2,
    themes: ["Fantastique"],
  },
  {
    name: "L'attaque des titans",
    src: "./images/SNK_modified.png",
    alt: "L'attaque des titans",
    favorite: true,
    number: 2,
    themes: ["Manga", "Anime", "pancarte"],
  },
];

export default images;
